# Generated by Django 2.2 on 2019-04-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('product', 'PRODUCT'), ('card', 'CARD'), ('gift card', 'GIFTCARD')], default='product', max_length=100),
        ),
    ]
