# Generated by Django 2.2 on 2019-04-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0004_auto_20190404_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcard',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_type',
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='occasion',
            field=models.CharField(choices=[('Birthday', 'BIRTHDAY'), ('Cheer Up', 'CHEERUP'), ('Congratulations', 'CONGRATULATIONS'), ('New Baby', 'NEWBABY'), ('Housewarming', 'HOUSEWARMING'), ('Breakup', 'BREAKUP'), ('Engagement', 'ENGAGEMENT'), ('Holiday', 'HOLIDAY'), ('New Job', 'NEWJOB'), ("Galentine's Day", 'GALENTINESDAY'), ('For Mom', 'FORMOM'), ('For Dad', 'FORDAD'), ('Lux Box', 'LUXBOX')], default='Birthday', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='product_type',
            field=models.CharField(choices=[('Party Supply', 'PARTY SUPPLY'), ('Accessories', 'ACCESSORIES'), ('Jewelry', 'JEWELRY'), ('Houseware', 'HOUSEWARE'), ('Spa', 'SPA'), ('Candles', 'CANDLES'), ('Stationary', 'STATIONARY')], default='Party Supply', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Giftcard',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
