# Generated by Django 2.2 on 2019-04-04 23:42

from django.db import migrations


def seed(apps, schema_editor):
    Item = apps.get_model('gift', 'Item')

    Item(name='Sympathy card', picture='https://i.imgur.com/m1i0PEX.jpg',
         price=5, occasion='Cheer Up', product_type='Stationary').save()
    Item(name='Birthday card', picture='https://i.imgur.com/bxhikVd.jpg', price=5,
         occasion='Birthday', product_type='Stationary').save()
    Item(name='Tree card', picture='https://i.imgur.com/U9svFRB.jpg', price=5,
         occasion='Holiday', product_type='Stationary').save()
    Item(name='Graduation card', picture='https://i.imgur.com/bzlD0VG.jpg', price=5,
         occasion='Congratulations', product_type='Stationary').save()
    Item(name='Rainbow card', picture='https://i.imgur.com/N4HTutb.jpg', price=5,
         occasion='Cheer Up', product_type='Stationary').save()
    Item(name='Unicorn card', picture='https://i.imgur.com/XgyEf1e.jpg', price=5,
         occasion='Cheer Up', product_type='Stationary').save()
    Item(name='Hot Tea Kit', picture='https://i.imgur.com/GdIfQHq.jpg', price=14,
         occasion='Housewarming', product_type='Houseware').save()
    Item(name='Coloring Book', picture='https://i.imgur.com/x433K2a.jpg', price=11,
         occasion='Cheer Up', product_type='Stationary').save()
    Item(name='Body Scrub and Oil', picture='https://i.imgur.com/jPHlzrB.jpg', price=10,
         occasion='Galentine\'s Day', product_type='Spa').save()
    Item(name='Bath Bomb', picture='https://i.imgur.com/rRDVj8N.jpg', price=7,
         occasion='Galentine\'s Day', product_type='Spa').save()
    Item(name='Spa Gloves and Socks', picture='https://i.imgur.com/54q1Sfw.jpg', price=9,
         occasion='Housewarming', product_type='Spa').save()
    Item(name='Homesick candle', picture='https://i.imgur.com/A0fqdL7.jpg', price=12,
         occasion='Housewarming', product_type='Candles').save()


def fallow(apps, schema_editor):
    Item = apps.get_model('gift', 'Item')
    Item.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0005_auto_20190404_1841'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
